import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === "production";
const vaultPluginDir = "/Users/daniel/Obsidian/Leela Protocol/.obsidian/plugins/obsidian-drawthings";

const copyToVault = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd(() => {
      try {
        if (!fs.existsSync(vaultPluginDir)) {
          fs.mkdirSync(vaultPluginDir, { recursive: true });
        }
        fs.copyFileSync("main.js", path.join(vaultPluginDir, "main.js"));
        fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
        if (fs.existsSync("styles.css")) {
          fs.copyFileSync("styles.css", path.join(vaultPluginDir, "styles.css"));
        }
      } catch (err) {
        // Silently skip if running in sandbox or if destination is locked
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "child_process",
    "fs",
    "path",
    "os"
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [copyToVault],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
